# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9c191071757e30da55a8fbcc578e3aed544ee35af4b54e9c27f0549a30f62e699cb26c21f63fc8a7905da94ed490295bcf18335c6d38cd15a1204f2ea11f7e

test:
  secret_key_base: 55f2005879cd25531b90d18da5e0ff3c1403ce3c906b291bd9a3c88bb26dfd8974f1cc0eaee58b1743872c9241fbe689df534ba7610ed1e72d8cf8cf0eeca89c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
